<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>false</PublishAot>
        <AssemblyName>kit</AssemblyName>
        <Company>Caprine Logic</Company>
        <ApplicationIcon>..\assets\icon.ico</ApplicationIcon>
        <AssemblyVersion>0.5.0</AssemblyVersion>
        <FileVersion>0.5.0</FileVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="YamlDotNet" Version="18.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Shared\UpdaterConfiguration.cs" Link="Shared\UpdaterConfiguration.cs"/>
        <Compile Include="..\Shared\StampPayload.cs" Link="Shared\StampPayload.cs" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\assets\icon.ico">
        <Link>icon.ico</Link>
      </None>
    </ItemGroup>
</Project>
